server {
    listen 80;
    server_name _;

    # Redirect HTTP → HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/server.crt;
    ssl_certificate_key /etc/nginx/certs/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    # Static files
    location /static/ {
        alias /app/staticfiles/;
        # Explicitly sets the expiration header to 1 day
        expires 1d;

        # Tells Cloudflare to cache for 1 day, then force a revalidation with EC2
        add_header Cache-Control "public, max-age=86400, must-revalidate";
    }

    # Media files (user uploads)
    location /media/ {
        alias /app/media/;
        # Explicitly sets the expiration header to 1 day
        expires 1d;

        # Tells Cloudflare to cache for 1 day, then force a revalidation with EC2
        add_header Cache-Control "public, max-age=86400, must-revalidate";
    }

    # Django via Gunicorn
    location / {
        proxy_pass http://web:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}