# Generated by Django 5.0.14 on 2026-06-09 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BibleVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_verse", models.IntegerField(db_index=True)),
                ("end_verse", models.IntegerField(db_index=True, null=True)),
                ("verse_text", models.TextField()),
                ("book_name", models.CharField(max_length=100)),
                ("chapter_number", models.IntegerField()),
                ("verse_id", models.CharField(max_length=100)),
                ("date", models.DateField(unique=True)),
            ],
            options={
                "ordering": ["book_name", "chapter_number", "start_verse", "end_verse"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("caption", models.CharField(max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("poster", models.ImageField(upload_to="events/")),
                ("ministry", models.JSONField(blank=True, default=list)),
                ("closed", models.BooleanField(default=False)),
                ("registration_link", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrayerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Thanksgiving", "Thanksgiving"),
                            ("Healing and Good Health", "Healing and Good Health"),
                            ("Souls", "Souls"),
                            ("Financial Abundance", "Financial Abundance"),
                            ("Guidance and Protection", "Guidance and Protection"),
                            ("Special Intentions", "Special Intentions"),
                        ],
                        default="Others",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "month",
                    models.CharField(
                        choices=[
                            ("January", "January"),
                            ("February", "February"),
                            ("March", "March"),
                            ("April", "April"),
                            ("May", "May"),
                            ("June", "June"),
                            ("July", "July"),
                            ("August", "August"),
                            ("September", "September"),
                            ("October", "October"),
                            ("November", "November"),
                            ("December", "December"),
                        ],
                        default="January",
                        max_length=20,
                    ),
                ),
                (
                    "week",
                    models.IntegerField(
                        choices=[
                            (1, "Week 1"),
                            (2, "Week 2"),
                            (3, "Week 3"),
                            (4, "Week 4"),
                            (5, "Week 5"),
                        ],
                        default=1,
                    ),
                ),
                ("year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("birthday", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "facebook_page",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("ministry", models.JSONField(blank=True, default=list)),
                (
                    "priority_ministry",
                    models.CharField(
                        choices=[
                            ("AKM", "AKM"),
                            ("Mercy", "Mercy"),
                            ("Couples", "Couples"),
                            ("Worship", "Worship"),
                            ("Liturgy", "Liturgy"),
                            ("Events", "Events"),
                            ("Media", "Media"),
                            ("No ministry yet", "No ministry yet"),
                        ],
                        default="No ministry yet",
                        max_length=50,
                    ),
                ),
                (
                    "spouse",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="married_to",
                        to="ministryhub.profile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
