# Generated by Django 5.0.14 on 2026-05-14 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_verse', models.IntegerField(db_index=True)),
                ('end_verse', models.IntegerField(db_index=True, null=True)),
                ('verse_text', models.TextField()),
                ('book_name', models.CharField(max_length=100)),
                ('chapter_number', models.IntegerField()),
                ('verse_id', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['book_name', 'chapter_number', 'start_verse', 'end_verse'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='events/')),
                ('ministry', models.JSONField(blank=True, default=list)),
                ('closed', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('facebook_page', models.CharField(blank=True, max_length=150, null=True)),
                ('ministry', models.JSONField(blank=True, default=list)),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouses', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
