# Generated by Django 5.0.14 on 2026-06-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ministryhub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="priority_ministry",
            field=models.CharField(
                choices=[
                    ("AKM", "AKM"),
                    ("Couples", "Couples"),
                    ("Events", "Events"),
                    ("Finance", "Finance"),
                    ("Liturgy", "Liturgy"),
                    ("Mercy", "Mercy"),
                    ("Media", "Media"),
                    ("Worship", "Worship"),
                    ("No ministry yet", "No ministry yet"),
                ],
                default="No ministry yet",
                max_length=50,
            ),
        ),
    ]
